name: CI and Publish

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    name: Build with Gradle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: |
          ./gradlew :paper:build
          ./gradlew :velocity:build
          ./gradlew chiseledBuildAndCollect

      - name: Publish to Modrinth
        if: github.branch == 'master'
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        run: |
          ./gradlew :paper:modrinth
          ./gradlew :fabric:chiseledPublish

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AntiCrasher-${{ env.version }}+${{ github.run_number }}
          path: |
            libs/AntiCrasher-*.jar